services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
      - "38281-38301:38281-38301"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
  
  frontend:
    build: ./frontend
    ports: 
      - "5173:5173"
    depends_on:
      - backend